namespace Altemiq.Patterns.Builder.Generator;

using Microsoft.CodeAnalysis;

public class BuilderGeneratorTests
{
    [Test]
    public async Task TestCaching()
    {
        var compilation = Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create("TestProject",
            [
            Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText("""
                namespace MyCode
                {
                    [Altemiq.Patterns.Builder.GenerateBuilder]
                    public partial class Test
                    {
                        public int PrimitiveValue { get; set; }
                    }
                }
                """)
            ],
            [
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(GenerateBuilderAttribute).Assembly.Location),
            ],
            new Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new BuilderGenerator();
        var sourceGenerator = generator.AsSourceGenerator();

        // trackIncrementalGeneratorSteps allows to report info about each step of the generator
        GeneratorDriver driver = Microsoft.CodeAnalysis.CSharp.CSharpGeneratorDriver.Create(
            generators: [sourceGenerator],
            driverOptions: new(default, trackIncrementalGeneratorSteps: true));

        // Run the generator
        driver = driver.RunGenerators(compilation);

        // Update the compilation and rerun the generator
        compilation = compilation.AddSyntaxTrees(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText("// dummy"));
        driver = driver.RunGenerators(compilation);

        // Assert the driver doesn't recompute the output
        var result = driver.GetRunResult().Results.Single();
        var allOutputs = result
            .TrackedOutputSteps
            .SelectMany(outputStep => outputStep.Value)
            .SelectMany(output => output.Outputs);
        await Assert.That(allOutputs).All(output => output.Reason is IncrementalStepRunReason.Cached);

        // Assert the driver use the cached result from InitialExtraction and RemovingNulls
        await Assert.That(result.TrackedSteps["InitialExtraction"].Single().Outputs).All(output => output.Reason is IncrementalStepRunReason.Unchanged);
        await Assert.That(result.TrackedSteps["RemovingNulls"].Single().Outputs).All(output => output.Reason is IncrementalStepRunReason.Unchanged or IncrementalStepRunReason.Cached);
    }

    [Test]
    public async Task TestPrimitive()
    {
        var context = new CSharpSourceGeneratorTest<BuilderGenerator, DefaultVerifier>
        {
            ReferenceAssemblies = GetReferenceAssemblies(),
            TestCode =
                """
                namespace MyCode
                {
                    [Altemiq.Patterns.Builder.GenerateBuilder]
                    public partial class Test
                    {
                        public int PrimitiveValue { get; set; }
                    }
                }
                """,
            TestState =
            {
                AdditionalReferences =
                {
                    // Add the attribute assembly.
                    typeof(GenerateBuilderAttribute).Assembly
                },
                GeneratedSources =
                {
                    (
                        typeof(BuilderGenerator),
                        "Test.Builder.g.cs",
                        """
                        // <autogenerated />
                        namespace MyCode
                        {
                            ///<content>The <see cref = "Test"/> builder methods.</content>
                            partial class Test
                            {
                                ///<summary>Creates a new builder for a <see cref = "Test"/> instance.</summary>
                                public static TestBuilder CreateBuilder()
                                {
                                    return new TestBuilder();
                                }

                                ///<summary>The <see cref = "Test"/> builder.</summary>
                                public sealed partial class TestBuilder
                                {
                                    private int primitiveValue;
                                    ///<summary>Sets the <see cref = "Test.PrimitiveValue"/> value.</summary>
                                    ///<param name = "primitiveValue">The primitive value value.</param>
                                    ///<returns>The builder for chaining.</returns>
                                    public TestBuilder WithPrimitiveValue(int primitiveValue)
                                    {
                                        this.primitiveValue = primitiveValue;
                                        return this;
                                    }
                    
                                    ///<summary>Builds an instance of <see cref = "Test"/>.</summary>
                                    ///<returns>The instance of <see cref = "Test"/>.</returns>
                                    public Test Build()
                                    {
                                        var value = new Test()
                                        {
                                            PrimitiveValue = this.primitiveValue
                                        };
                                        return value;
                                    }
                                }
                            }
                        }
                        """)
                }
            }
        };

        await context.RunAsync(TestContext.Current?.Execution.CancellationToken ?? CancellationToken.None);
    }

    [Test]
    public async Task TestLazy()
    {
        var context = new CSharpSourceGeneratorTest<BuilderGenerator, DefaultVerifier>
        {
            ReferenceAssemblies = GetReferenceAssemblies(),
            TestCode =
                """
                namespace MyCode
                {
                    [Altemiq.Patterns.Builder.GenerateBuilder]
                    public partial class Test
                    {
                        public System.DateTime DateTimeValue { get; set; }
                    }
                }
                """,
            TestState =
            {
                AdditionalReferences =
                {
                    // Add the attribute assembly.
                    typeof(GenerateBuilderAttribute).Assembly
                },
                GeneratedSources =
                {
                    (
                        typeof(BuilderGenerator),
                        "Test.Builder.g.cs",
                        """
                        // <autogenerated />
                        namespace MyCode
                        {
                            ///<content>The <see cref = "Test"/> builder methods.</content>
                            partial class Test
                            {
                                ///<summary>Creates a new builder for a <see cref = "Test"/> instance.</summary>
                                public static TestBuilder CreateBuilder()
                                {
                                    return new TestBuilder();
                                }

                                ///<summary>The <see cref = "Test"/> builder.</summary>
                                public sealed partial class TestBuilder
                                {
                                    private System.Lazy<System.DateTime> dateTimeValue = new System.Lazy<System.DateTime>(() => default);
                                    ///<summary>Sets the <see cref = "Test.DateTimeValue"/> value.</summary>
                                    ///<param name = "dateTimeValue">The date time value value.</param>
                                    ///<returns>The builder for chaining.</returns>
                                    public TestBuilder WithDateTimeValue(System.DateTime dateTimeValue)
                                    {
                                        this.dateTimeValue = new System.Lazy<System.DateTime>(() => dateTimeValue);
                                        return this;
                                    }

                                    ///<summary>Sets the <see cref = "Test.DateTimeValue"/> value via a factory.</summary>
                                    ///<param name = "dateTimeValue">The date time value factory.</param>
                                    ///<returns>The builder for chaining.</returns>
                                    public TestBuilder WithDateTimeValue(System.Func<System.DateTime> dateTimeValue)
                                    {
                                        this.dateTimeValue = new System.Lazy<System.DateTime>(dateTimeValue);
                                        return this;
                                    }
                    
                                    ///<summary>Builds an instance of <see cref = "Test"/>.</summary>
                                    ///<returns>The instance of <see cref = "Test"/>.</returns>
                                    public Test Build()
                                    {
                                        var value = new Test()
                                        {
                                            DateTimeValue = this.dateTimeValue.Value
                                        };
                                        return value;
                                    }
                                }
                            }
                        }
                        """)
                }
            }
        };

        await context.RunAsync(TestContext.Current?.Execution.CancellationToken ?? CancellationToken.None);
    }

    private static ReferenceAssemblies GetReferenceAssemblies()
    {
#if NET10_0_OR_GREATER
        return ReferenceAssemblies.Net.Net100;
#elif NET9_0_OR_GREATER
        return ReferenceAssemblies.Net.Net90;
#elif NET8_0_OR_GREATER
        return ReferenceAssemblies.Net.Net80;
#elif NET7_0_OR_GREATER
        return ReferenceAssemblies.Net.Net70;
#elif NET6_0_OR_GREATER
        return ReferenceAssemblies.Net.Net60;
#elif NET5_0_OR_GREATER
        return ReferenceAssemblies.Net.Net50;
#elif NETCOREAPP3_1_OR_GREATER
        return ReferenceAssemblies.NetCore.NetCoreApp31;
#elif NETCOREAPP3_0_OR_GREATER
        return ReferenceAssemblies.NetCore.NetCoreApp30;
#elif NETCOREAPP2_1_OR_GREATER
        return ReferenceAssemblies.NetCore.NetCoreApp21;
#elif NETCOREAPP2_0_OR_GREATER
        return ReferenceAssemblies.NetCore.NetCoreApp20;
#elif NETCOREAPP1_1_OR_GREATER
        return ReferenceAssemblies.NetCore.NetCoreApp11;
#elif NETCOREAPP1_0_OR_GREATER
        return ReferenceAssemblies.NetCore.NetCoreApp10;
#endif
    }
}
