// -----------------------------------------------------------------------
// <copyright file="InternalGenerator.cs" company="Altemiq">
// Copyright (c) Altemiq. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace Altemiq.Patterns.Builder.Generator;

using Humanizer;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

/// <summary>
/// The internal generator.
/// </summary>
internal static partial class InternalGenerator
{
    private const string Key = "key";
    private const string Value = "value";
    private const string Item = "item";
    private const string KeyValuePair = "kvp";

    private const string NewLine = @"
";

    private static readonly XmlElementSyntax BuilderReturn = XmlReturnsElement(XmlText("The builder for chaining."));

    /// <summary>
    /// Generates the builder.
    /// </summary>
    /// <param name="context">The context.</param>
    /// <returns>The generated builder.</returns>
    public static CompilationUnitSyntax GenerateNestedBuilder(BuilderToGenerate context) => InNamespace(
            context.Namespace,
            SingletonList<MemberDeclarationSyntax>(
            ClassDeclaration(context.ClassName)
            .WithModifiers(TokenList(Token(SyntaxKind.PartialKeyword)))
            .WithLeadingTrivia(
            Trivia(
                DocumentationComment(
                    XmlMultiLineElement(
                        "content",
                        List<XmlNodeSyntax>(
                        [
                            XmlText("The "),
                            XmlSeeElement(
                                NameMemberCref(
                                    IdentifierName(context.ClassName))),
                            XmlText(" builder methods."),
                        ])),
                    XmlText(XmlTextNewLine(NewLine, continueXmlDocumentationComment: false)))))
            .WithMembers(
                List<MemberDeclarationSyntax>(
                    [
                    MethodDeclaration(
                        IdentifierName(context.BuilderName),
                        Identifier("CreateBuilder"))
                    .WithModifiers(
                        TokenList(
                            Token(SyntaxKind.PublicKeyword),
                            Token(SyntaxKind.StaticKeyword)))
                    .WithLeadingTrivia(
                        Trivia(
                            DocumentationComment(
                                XmlSummaryElement(
                                    XmlText("Creates a new builder for a "),
                                    XmlSeeElement(
                                        NameMemberCref(
                                            IdentifierName(context.ClassName))),
                                    XmlText(" instance.")),
                                XmlText(XmlTextNewLine(NewLine, continueXmlDocumentationComment: false)))))
                    .WithBody(
                        Block(
                            SingletonList<StatementSyntax>(
                                ReturnStatement(
                                    ObjectCreationExpression(
                                        IdentifierName(context.BuilderName))
                                    .WithArgumentList(
                                        ArgumentList()))))),
                    GenerateBuilder(context),
                ]))));

    private static CompilationUnitSyntax InNamespace(string @namespace, SyntaxList<MemberDeclarationSyntax> members) => CompilationUnit()
        .WithMembers(
        SingletonList<MemberDeclarationSyntax>(
            NamespaceDeclaration(NameHelpers.GetQualifiedName(@namespace))
            .WithLeadingTrivia(Comment("// <autogenerated />"))
            .WithMembers(members)));

    private static ClassDeclarationSyntax GenerateBuilder(BuilderToGenerate context)
    {
        return ClassDeclaration(context.BuilderName)
            .WithModifiers(
            TokenList(
                Token(SyntaxKind.PublicKeyword),
                Token(SyntaxKind.SealedKeyword),
                Token(SyntaxKind.PartialKeyword)))
            .WithLeadingTrivia(
            Trivia(
                DocumentationComment(
                    XmlSummaryElement(
                        XmlText("The "),
                        XmlSeeElement(
                            NameMemberCref(
                                IdentifierName(context.ClassName))),
                        XmlText(" builder.")),
                    XmlText(XmlTextNewLine(NewLine, continueXmlDocumentationComment: false)))))
            .WithMembers([.. CreateMembers(context)]);

        static IEnumerable<MemberDeclarationSyntax> CreateMembers(BuilderToGenerate context)
        {
            foreach (var property in context.Properties)
            {
                if (property.ReadOnly)
                {
                    // check to see if the type is a read-only collection
                    if (property.Dictionary)
                    {
                        foreach (var member in CreateDictionaryMembers(context.ClassName, context.BuilderName, property))
                        {
                            yield return member;
                        }

                        continue;
                    }

                    // check to see if the type is a read-only collection
                    if (property.Collection)
                    {
                        foreach (var member in CreateCollectionMembers(context.ClassName, context.BuilderName, property))
                        {
                            yield return member;
                        }

                        continue;
                    }
                }

                // check to see if the type is a primitive
                if (property.Primitive)
                {
                    foreach (var member in CreatePrimitive(context.ClassName, context.BuilderName, property))
                    {
                        yield return member;
                    }

                    continue;
                }

                foreach (var member in CreateLazy(context.ClassName, context.BuilderName, property))
                {
                    yield return member;
                }
            }

            // return the build method
            yield return MethodDeclaration(
                IdentifierName(context.ClassName),
                Identifier("Build"))
                .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PublicKeyword)))
                .WithLeadingTrivia(
                Trivia(
                    DocumentationComment(
                        XmlSummaryElement(
                            XmlText("Builds an instance of "),
                            XmlSeeElement(
                                NameMemberCref(
                                    IdentifierName(context.ClassName))),
                            XmlText(".")),
                        XmlText(XmlTextNewLine(NewLine)),
                        XmlReturnsElement(
                            XmlText("The instance of "),
                            XmlSeeElement(
                                NameMemberCref(
                                    IdentifierName(context.ClassName))),
                            XmlText(".")),
                        XmlText(XmlTextNewLine(NewLine, continueXmlDocumentationComment: false)))))
                .WithBody(
                Block(
                    GetBodyStatements(context)));

            static IEnumerable<StatementSyntax> GetBodyStatements(BuilderToGenerate context)
            {
                yield return LocalDeclarationStatement(
                        VariableDeclaration(
                            IdentifierName(
                                Identifier(
                                    TriviaList(),
                                    SyntaxKind.VarKeyword,
                                    "var",
                                    "var",
                                    TriviaList())))
                        .WithVariables(
                            SingletonSeparatedList<VariableDeclaratorSyntax>(
                                VariableDeclarator(
                                    Identifier(Value))
                                .WithInitializer(
                                    EqualsValueClause(
                                        ObjectCreationExpression(
                                            IdentifierName(context.ClassName))
                                        .WithArgumentList(
                                            ArgumentList())
                                        .WithInitializer(
                                            InitializerExpression(
                                                SyntaxKind.ObjectInitializerExpression,
                                                SeparatedList<ExpressionSyntax>(
                                                    GetAssignmentExpressions(context.Properties)))))))));

                foreach (var collection in GetCollectionAssignment(context.Properties))
                {
                    yield return collection;
                }

                foreach (var dictionary in GetDictionaryAssignment(context.Properties))
                {
                    yield return dictionary;
                }

                yield return ReturnStatement(IdentifierName(Value));

                static IEnumerable<ExpressionSyntax> GetAssignmentExpressions(IEnumerable<PropertyToGenerate> properties)
                {
                    return properties
                        .Where(property => !property.ReadOnly)
                        .Select(property =>
                            AssignmentExpression(
                                SyntaxKind.SimpleAssignmentExpression,
                                IdentifierName(property.Name),
                                GetMemberAccess(property)));

                    static MemberAccessExpressionSyntax GetMemberAccess(PropertyToGenerate property)
                    {
                        var memberAccess = MemberAccessExpression(
                                    SyntaxKind.SimpleMemberAccessExpression,
                                    ThisExpression(),
                                    IdentifierName(property.FieldName));
                        if (!property.Primitive)
                        {
                            memberAccess = MemberAccessExpression(
                                SyntaxKind.SimpleMemberAccessExpression,
                                memberAccess,
                                IdentifierName(nameof(Lazy<>.Value)));
                        }

                        return memberAccess;
                    }
                }
            }
        }
    }

    private static SeparatedSyntaxList<TypeSyntax> GetTypeArguments(TypeSyntax typeSyntax)
    {
        if (typeSyntax is QualifiedNameSyntax { Right: GenericNameSyntax { TypeArgumentList.Arguments: { } arguments } })
        {
            return arguments;
        }

        throw new InvalidOperationException();
    }
}